version: '3'
services:
  db:
    container_name: postgres
    image: postgres:11.3-alpine
    environment:
      POSTGRES_SUPERUSER: postgres
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: pp_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
        - 127.0.0.1:5432:5432

  
volumes:
  pgdata: